### PR TITLE
Node body check - with tests

### PR DESCRIPTION
**Pull request by soda0289**
I added tests but they still fail. It looks like more work will be done to correct all the uses of node.body. We could add an empty body but would like your opinion first on how to proceed.

### CODE REVIEW

**Comment by soda0289** [comment]
Here is the stack trace:
```
     TypeError: Cannot read property 'body' of null
      at isStrictScope (src/scope.js:82:26)
      at FunctionScope.Scope (src/scope.js:219:25)
      at new FunctionScope (src/scope.js:585:70)
      at ScopeManager.__nestFunctionScope (src/scope-manager.js:205:33)
      at Referencer.visitFunction (src/referencer.js:192:27)
      at Referencer.FunctionExpression (src/referencer.js:534:14)
      at Referencer.Visitor.visit (node_modules/esrecurse/esrecurse.js:122:34)
      at Referencer.Visitor.visitChildren (node_modules/esrecurse/esrecurse.js:106:26)
      at Referencer.Visitor.visit (node_modules/esrecurse/esrecurse.js:125:14)
      at Referencer.Visitor.visitChildren (node_modules/esrecurse/esrecurse.js:101:38)
```

**Comment by soda0289** [comment]
I found a quick fix will update soon.

**Comment by soda0289** [comment]
Will need to spend more time looking into why the scope is being generated the way it is. Not sure if the results are correct

**Comment by corbinu** [comment]
@soda0289 Would you be cool with me merging this so we can get multiple call signatures in. Figure we can do Abstract classes in another PR if that requires more changes to eslint-scope :)

**Comment by soda0289** [comment]
@corbinu Sure thing will submit with just multiple call signatures.

**Comment by soda0289** [comment]
I pushed the change. I will spend some time looking into later tonight and open another PR with changes for Abstract Class.

**Pull request merged**
